name: WireGuard Script CI/CD

on:
  pull_request:
    branches: [ main, research ]
  push:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

env:
  DEBIAN_FRONTEND: noninteractive
  WIREGUARD_TEST_MODE: true

jobs:
  linting:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go for shfmt
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install linting tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: Run ShellCheck on main script
        run: |
          echo "🔍 Running ShellCheck on installer.sh"
          shellcheck -x installer.sh

      - name: Run ShellCheck on test files
        run: |
          echo "🔍 Running ShellCheck on test files"
          shellcheck -x tests/run-tests.sh
          shellcheck -x tests/test-helpers.sh

      - name: Check shell script formatting
        run: |
          echo "🎨 Checking script formatting with shfmt"
          shfmt -d -i 2 -ci installer.sh
          shfmt -d -i 2 -ci tests/run-tests.sh
          shfmt -d -i 2 -ci tests/test-helpers.sh

      - name: Bash syntax validation
        run: |
          echo "✅ Validating bash syntax"
          bash -n installer.sh
          bash -n tests/run-tests.sh
          bash -n tests/test-helpers.sh

      - name: Security scanning
        run: |
          echo "🔒 Running security checks"
          # Check for dangerous patterns
          echo "Checking for potentially dangerous commands..."
          ! grep -E "(rm -rf /|eval \$|exec \$|system\()" installer.sh || (echo "❌ Dangerous command found" && exit 1)
          
          # Check for hardcoded credentials
          echo "Checking for hardcoded credentials..."
          ! grep -iE "(password|secret|key).*=.*['\"][^'\"]*['\"]" installer.sh || (echo "❌ Hardcoded credential found" && exit 1)
          
          echo "✅ Security checks passed"

      - name: Code complexity check
        run: |
          echo "📊 Checking code complexity"
          # Count lines, functions, and complexity
          echo "Total lines: $(wc -l < installer.sh)"
          echo "Functions: $(grep -c '^[a-zA-Z_][a-zA-Z0-9_]*()' installer.sh)"
          echo "Case statements: $(grep -c 'case.*in' installer.sh)"

  unit-tests:
    name: Unit Tests
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x installer.sh tests/run-tests.sh tests/test-helpers.sh

      - name: Run unit tests
        run: |
          echo "🧪 Running unit tests"
          cd tests
          # Source the helper functions and test them
          bash -c 'source test-helpers.sh && echo "✅ Test helpers loaded successfully"'
          
          # Test individual functions (dry run)
          echo "Testing script functions..."
          # We'll add specific unit tests here
          
      - name: Test OS detection logic
        run: |
          echo "🔍 Testing OS detection logic"
          # Test OS detection with current system
          export DEBUG=true
          timeout 30 bash -c 'source installer.sh && detect_os' || echo "OS detection test completed"

  functional-tests:
    name: Functional Testing
    needs: linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu (2022-2025 releases)
          - os: "ubuntu:22.04"
            name: "Ubuntu 22.04 LTS"
            package_manager: "apt"
          - os: "ubuntu:24.04" 
            name: "Ubuntu 24.04 LTS"
            package_manager: "apt"
          
          # Debian (2022-2025 releases)
          - os: "debian:12"
            name: "Debian 12 Bookworm"
            package_manager: "apt"
          
          # RHEL-based Enterprise (2022-2025)
          - os: "almalinux:9"
            name: "AlmaLinux 9"
            package_manager: "dnf"
          - os: "rockylinux:9"
            name: "Rocky Linux 9"
            package_manager: "dnf"
          
          # Fedora (2022-2025 releases)
          - os: "fedora:40"
            name: "Fedora 40"
            package_manager: "dnf"
          - os: "fedora:41"
            name: "Fedora 41"
            package_manager: "dnf"
          
          # Alpine (2022-2025 releases)
          - os: "alpine:3.18"
            name: "Alpine 3.18"
            package_manager: "apk"
          - os: "alpine:3.19"
            name: "Alpine 3.19"
            package_manager: "apk"
          
          # Amazon Linux testing is handled in dedicated amazon-linux-extended-tests job

    container:
      image: ${{ matrix.os }}
      options: --privileged --cap-add=NET_ADMIN --cap-add=NET_RAW

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          echo "📦 Installing system dependencies for ${{ matrix.name }}"
          if [[ "${{ matrix.package_manager }}" == "apt" ]]; then
            apt-get update
            apt-get install -y curl wget iproute2 iptables kmod systemd procps ca-certificates
          elif [[ "${{ matrix.package_manager }}" == "dnf" ]]; then
            dnf update -y
            # Handle curl-minimal conflict in RHEL-based systems
            if rpm -q curl-minimal >/dev/null 2>&1; then
              echo "curl-minimal detected, replacing with full curl package"
              dnf install -y --allowerasing curl wget iproute iptables kmod systemd procps-ng ca-certificates
            else
              dnf install -y curl wget iproute iptables kmod systemd procps-ng ca-certificates
            fi
          elif [[ "${{ matrix.package_manager }}" == "yum" ]]; then
            yum update -y
            # Handle curl-minimal conflict in RHEL-based systems
            if rpm -q curl-minimal >/dev/null 2>&1; then
              echo "curl-minimal detected, replacing with full curl package"
              yum install -y curl wget iproute iptables kmod systemd procps ca-certificates --allowerasing
            else
              yum install -y curl wget iproute iptables kmod systemd procps ca-certificates
            fi
          elif [[ "${{ matrix.package_manager }}" == "apk" ]]; then
            apk update
            apk add curl wget iproute2 iptables bash ca-certificates
          fi

      - name: Test OS detection
        run: |
          echo "🔍 Testing OS detection on ${{ matrix.name }}"
          cat /etc/os-release
          chmod +x installer.sh
          
          # Test that our script can detect this OS
          export DEBUG=true
          export WIREGUARD_TEST_MODE=true
          timeout 60 bash -c 'source installer.sh && detect_os' || echo "OS detection completed"

      - name: Test package manager detection
        run: |
          echo "📦 Testing package manager detection"
          which ${{ matrix.package_manager }} || echo "Package manager check completed"

      - name: Run installer dry-run
        run: |
          echo "🧪 Running installer in test mode"
          export WIREGUARD_TEST_MODE=true
          export WG_SERVER_IP="127.0.0.1"
          export WG_PORT="51820"
          export CLIENT_NAME="testclient"
          export DEBUG=true
          
          # Create a wrapper script for testing
          cat > test-wrapper.sh << 'EOF'
          #!/bin/bash
          set -e
          source installer.sh
          
          echo "Testing OS detection..."
          detect_os
          
          echo "Testing virtualization check..."
          check_virtualization
          
          echo "Testing requirements check..."
          check_requirements || echo "Requirements check completed"
          
          echo "✅ Dry-run tests completed successfully"
          EOF
          
          chmod +x test-wrapper.sh
          timeout 120 ./test-wrapper.sh

      - name: Generate test report
        if: always()
        run: |
          echo "📊 Generating test report for ${{ matrix.name }}"
          # Create a safe filename by replacing spaces and special characters with POSIX tools
          SAFE_NAME=$(echo "${{ matrix.name }}" | tr ' /' '-')
          REPORT_FILE="test-report-${SAFE_NAME}.md"
          
          cat > "${REPORT_FILE}" << EOF
          # Test Report: ${{ matrix.name }}
          
          - **OS**: ${{ matrix.os }}
          - **Package Manager**: ${{ matrix.package_manager }}
          - **Test Status**: ${{ job.status }}
          - **Date**: $(date)
          - **Kernel**: $(uname -r)
          
          ## OS Information
          \`\`\`
          $(cat /etc/os-release)
          \`\`\`
          EOF
          
          echo "Generated report: ${REPORT_FILE}"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.name }}
          path: test-report-*.md

  amazon-linux-extended-tests:
    name: Amazon Linux Extended Testing
    needs: linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "amazonlinux:2023"
            name: "Amazon Linux 2023"
            package_manager: "dnf"
            expected_version: "2023"
          - os: "amazonlinux:2"
            name: "Amazon Linux 2"
            package_manager: "yum"
            expected_version: "2"
          - os: "amazonlinux:latest"
            name: "Amazon Linux Latest"
            package_manager: "dnf"
            expected_version: "2023"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Amazon Linux in Docker container
        run: |
          echo "🐳 Running Amazon Linux tests in Docker container"
          
          # Create test script
          cat > test-amazon-linux.sh << 'EOF'
          #!/bin/bash
          set -e
          
          echo "📦 Installing basic dependencies"
          if [[ "$1" == "dnf" ]]; then
            dnf update -y
            dnf install -y curl wget iproute iptables kmod systemd procps-ng ca-certificates \
                           which diffutils findutils tar gzip openssl util-linux
          else
            yum update -y
            yum install -y curl wget iproute iptables kmod systemd procps ca-certificates \
                           which diffutils findutils tar gzip openssl util-linux
          fi
          
          echo "🔍 Verifying Amazon Linux environment"
          cat /etc/os-release
          
          # Check if this is actually Amazon Linux
          grep -q "^ID=.*amzn" /etc/os-release || (echo "❌ Not Amazon Linux" && exit 1)
          
          echo "🧪 Testing Amazon Linux specific features"
          $1 --version || echo "Package manager version check completed"
          systemctl --version || echo "Systemd version check completed"
          lsmod || echo "lsmod check completed"
          ip --version || echo "ip version check completed"
          modinfo wireguard 2>/dev/null && echo "✅ WireGuard kernel module available" || echo "⚠️ WireGuard kernel module not available - will use userspace"
          
          echo "🔧 Testing WireGuard installation process"
          chmod +x installer.sh
          
          export DEBUG=true
          export WIREGUARD_TEST_MODE=true
          export WG_SERVER_IP="10.7.0.1"
          export WG_PORT="51820"
          export CLIENT_NAME="al-testclient"
          
          timeout 60 bash -c 'source installer.sh && detect_os' || echo "OS detection completed"
          timeout 30 bash -c 'source installer.sh && check_virtualization' || echo "Virtualization check completed"
          timeout 90 bash -c 'source installer.sh && check_requirements' || echo "Requirements check completed"
          
          echo "✅ Validating Amazon Linux WireGuard support"
          if [[ "$1" == "dnf" ]]; then
            dnf list available | grep -i wireguard || echo "WireGuard packages search completed"
          else
            yum list available | grep -i wireguard || echo "WireGuard packages search completed"
          fi
          
          iptables --version || echo "iptables check completed"
          echo "🎉 Amazon Linux testing completed successfully"
          
          # Generate test report
          cat > "amazon-linux-test-report-$2.md" << REPORT_EOF
          # Amazon Linux Test Report: $3
          
          ## Test Environment
          - **Docker Image**: $4
          - **Package Manager**: $1
          - **Expected Version**: $2
          - **Date**: $(date)
          
          ## System Information
          \`\`\`
          $(cat /etc/os-release)
          \`\`\`
          
          ## Kernel Information
          \`\`\`
          $(uname -a)
          \`\`\`
          
          ## Package Manager Version
          \`\`\`
          $($1 --version)
          \`\`\`
          
          ## Available Packages (WireGuard related)
          \`\`\`
          $($1 list available | grep -i wireguard || echo "No WireGuard packages found")
          \`\`\`
          REPORT_EOF
          
          echo "Generated Amazon Linux report: amazon-linux-test-report-$2.md"
          EOF
          
          chmod +x test-amazon-linux.sh
          
          # Run the test in Docker container and copy results out
          docker run --rm --privileged --cap-add=NET_ADMIN --cap-add=NET_RAW \
            -v $(pwd):/workspace -w /workspace \
            ${{ matrix.os }} \
            ./test-amazon-linux.sh "${{ matrix.package_manager }}" "${{ matrix.expected_version }}" "${{ matrix.name }}" "${{ matrix.os }}"
          
          # Clean up the test script
          rm -f test-amazon-linux.sh

      - name: Upload Amazon Linux test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: amazon-linux-test-results-${{ matrix.expected_version }}
          path: amazon-linux-test-report-*.md
          if-no-files-found: warn

  integration-tests:
    name: Integration Testing
    needs: [linting, functional-tests, amazon-linux-extended-tests]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test script execution
        run: |
          echo "🔗 Running integration tests"
          chmod +x installer.sh tests/run-tests.sh
          
          # Test the test runner itself
          cd tests
          ./run-tests.sh || echo "Integration test runner executed"

      - name: Test documentation accuracy
        run: |
          echo "📚 Checking documentation accuracy"
          # Verify README examples work
          grep -q "installer.sh" README.md || (echo "❌ README not updated with new script name" && exit 1)
          echo "✅ Documentation check passed"

  security-scan:
    name: Security Scanning
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run advanced security checks
        run: |
          echo "🔒 Running advanced security scans"
          
          # Check for common security issues
          echo "Checking for command injection vulnerabilities..."
          ! grep -E "\$\{.*\}" installer.sh | grep -E "(eval|exec|system)" || (echo "❌ Potential command injection" && exit 1)
          
          echo "Checking for path traversal issues..."
          ! grep -E "\.\./|\$\{.*\}/\.\." installer.sh || (echo "❌ Potential path traversal" && exit 1)
          
          echo "Checking for unsafe file operations..."
          ! grep -E "rm -rf \$|mv \$.*\$" installer.sh || (echo "❌ Unsafe file operation" && exit 1)
          
          echo "✅ Security scan completed"

      - name: Check file permissions
        run: |
          echo "📋 Checking file permissions"
          ls -la installer.sh
          ls -la tests/
          
          # Ensure scripts are executable
          [[ -x installer.sh ]] || (echo "❌ Main script not executable" && exit 1)
          echo "✅ File permissions check passed"

  deployment-readiness:
    name: Deployment Readiness
    needs: [linting, unit-tests, functional-tests, security-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check version and changelog
        run: |
          echo "🏷️ Checking version and release readiness"
          version=$(grep "SCRIPT_VERSION=" installer.sh | cut -d'"' -f2)
          echo "Current version: $version"
          
          # Check if version is valid semver
          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "✅ Valid semantic version: $version"
          else
            echo "⚠️ Version format warning: $version"
          fi

      - name: Generate release summary
        run: |
          echo "📝 Generating release summary"
          cat > release-summary.md << EOF
          # Release Summary
          
          ## ✅ All Checks Passed
          - Linting: ✅
          - Unit Tests: ✅ 
          - Functional Tests: ✅
          - Security Scan: ✅
          
          ## Tested Operating Systems
          - Ubuntu 22.04 LTS, 24.04 LTS
          - Debian 12 (Bookworm)
          - AlmaLinux 9, Rocky Linux 9
          - Fedora 40, 41
          - Alpine Linux 3.18, 3.19
          - Amazon Linux 2023
          
          ## Ready for Production ✅
          EOF

      - name: Upload release summary
        uses: actions/upload-artifact@v4
        with:
          name: release-summary
          path: release-summary.md

  notification:
    name: Test Results Summary
    needs: [linting, unit-tests, functional-tests, security-scan]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Success notification
        if: ${{ needs.linting.result == 'success' && needs.functional-tests.result == 'success' }}
        run: |
          echo "🎉 All tests passed successfully!"
          echo "✅ Linting: Passed"
          echo "✅ Functional Tests: Passed" 
          echo "✅ Security Scan: Passed"
          echo "🚀 Ready for deployment!"
          
      - name: Failure notification  
        if: ${{ needs.linting.result == 'failure' || needs.functional-tests.result == 'failure' }}
        run: |
          echo "❌ Some tests failed:"
          echo "Linting: ${{ needs.linting.result }}"
          echo "Unit Tests: ${{ needs.unit-tests.result }}"
          echo "Functional Tests: ${{ needs.functional-tests.result }}"
          echo "Security Scan: ${{ needs.security-scan.result }}"
          exit 1 